### ISSUE TITLE
Cannot start Video Stream

### ISSUE THREAD

**Issue by jolo22** [AzuraCast/radio-video-stream#1]
Hello, 

I can't start the videostream, I followed everything instructed on the readme.md file. 
Already tried using chmod with no luck.

Here is the error:
`Cannot start service videostream: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/var/azuracast/videostream/broadcast.sh\": permission denied": unknown`

**Comment by BusterNeece** [comment]
@jolo22 Should be fixed now. Try pulling down the updated Dockerfile and rebuilding.

**Comment by jolo22** [comment]
> @jolo22 Should be fixed now. Try pulling down the updated Dockerfile and rebuilding.

Thank you so much! everything is fine now and videostream container is now started. But I’m still figuring it out on how to use it, even though I putted my stream key on the .yml file, Its still offline on the YT Live Dashboard.

**Comment by BusterNeece** [comment]
@jolo22 You made sure to keep the entire youtube RTMP URL right? i.e. replacing only `aaaa-bbbb-cccc-dddd` with your key?

**Comment by dbeiner** [comment]
Hi,

Same issue here. YouTube stream is offline. I only replace the key and the VS_AUDIO_SOURCE URL...

Thx for your help!

**Comment by BusterNeece** [comment]
@dbeiner @jolo22 Try visiting the [YouTube Live Dashboard](https://www.youtube.com/live_dashboard) and checking the stream health. Also verify that the first part of the `VS_RTMP_SERVER` URL is correct for your account. The VS_RTMP_SERVER should be in the format: `rtmp://a.rtmp.youtube.com/live2/your-key-here`

**Comment by dbeiner** [comment]
Hi, thanks for your reply.
The stream health is good but offline. I re-checked all the VS_RTMP_SERVER URL and everything is fine but the stream doesn't start. I've tested a live stream with OBS, everything works fine...

**Comment by jolo22** [comment]
> @dbeiner @jolo22 Try visiting the [YouTube Live Dashboard](https://www.youtube.com/live_dashboard) and checking the stream health. Also verify that the first part of the `VS_RTMP_SERVER` URL is correct for your account. The VS_RTMP_SERVER should be in the format: `rtmp://a.rtmp.youtube.com/live2/your-key-here`

Yup I didn't touch anything on the RTMP URL, I just replaced the aaaa-bbbb-cccc-dddd part with my own key. And my stream health is good also, but the stream from videostream doesn't start.

**Comment by Siriusa77II** [comment]
Like I said in #2 Please double check your stream key sometimes this can change for some reason.
and to give you more information on our setup we running a developement node relaying our radio and cast it on youtube. (all nodes on NVME SSD)  
I dont know if it change anything but try restart your container with:
`docker-compose down`
`docker-compose up -d`
also try change your video in /var/azuracast/videostream/ by a smaller one (1080p or 720p)
I give a version of exemple.mp4 in #2 you just have to rename it or change the path in your `docker-compose.override.yml`.
and allow 5 minutes for the stream start. it can take a bit of time specially on small server.

**Comment by jolo22** [comment]
> Like I said in #2 Please double check your stream key sometimes this can change for some reason.
> and to give you more information on our setup we running a developement node relaying our radio and cast it on youtube. (all nodes on NVME SSD)
> I dont know if it change anything but try restart your container with:
> `docker-compose down`
> `docker-compose up -d`
> also try change your video in /var/azuracast/videostream/ by a smaller one (1080p or 720p)
> I give a version of exemple.mp4 in #2 you just have to rename it or change the path in your `docker-compose.override.yml`.
> and allow 5 minutes for the stream start. it can take a bit of time specially on small server.

Some update, I managed to replace the example.mp4 file and edit some parameters on docker-compose.override.yml file, I checked the "docker-compose logs" and the reason the stream wasn't starting its because my server was OOM aka Code 137. (I think because the server needs to re-encode a mp4 4k file) and some directories are not found in which I fixed them by installing needed dependencies and providing correct location on the yml and Dockerfile files. After that I rebuild the container and now the stream has started! thanks for all the help! hope everyone will have some success in testing this, a really cool feature! Hope this help! Ill close this now.
