### ISSUE TITLE
Stream Not Connecting

### ISSUE THREAD

**Issue by countrymusicfy** [AzuraCast/radio-video-stream#10]
I built and started radio-video-stream, but it is not connecting to youtube.  Appreciate any suggestions on how to fix ...

I ran "docker-compose logs -f videostream" and below is an example.

I notice there is no /var/azuracast/stations directory on the Ubuntu 20.04 server, Azuracast v0.10.2, #1c87b48

There is a /var/azuracast/videostream/nowplaying.txt

--------------------------------------------------------------------

Input #1, mp3, from 'https://example.com/radio/8000/radio.mp3':
videostream                |   Metadata:
videostream                |     icy-br          : 192
videostream                |     icy-description : Country
videostream                |     icy-genre       : Country
videostream                |     icy-name        : Country
videostream                |     icy-pub         : 0
videostream                |     icy-url         : https://example.com
videostream                |     StreamTitle     : Blake Shelton - Nobody But You (Duet with Gwen Stefani)
videostream                |   Duration: N/A, start: 0.000000, bitrate: 192 kb/s
videostream                |     Stream #1:0: Audio: mp3, 44100 Hz, stereo, s16p, 192 kb/s
videostream                | Stream mapping:
videostream                |   Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
videostream                |   Stream #1:0 -> #0:1 (mp3 (native) -> mp3 (libmp3lame))
videostream                | Press [q] to stop, [?] for help
videostream                | [Parsed_drawtext_0 @ 0x55dbb40cc6e0] [FILE @ 0x7ffcddd69f20] Cannot read file '/var/azuracast/stations/azuratest_radio/config/nowplaying.txt': No such file or directory
videostream                | [Parsed_drawtext_0 @ 0x55dbb40cc6e0] The text file '/var/azuracast/stations/azuratest_radio/config/nowplaying.txt' could not be read or is empty
videostream                | [AVFilterGraph @ 0x55dbb4629aa0] Error initializing filter 'drawtext' with args 'fontfile=/usr/share/fonts/truetype/ubuntu/Ubuntu-B.ttf: fontsize=55:      box=1: boxcolor=black@0.5: boxborderw=20:      textfile=/var/azuracast/stations/azuratest_radio/config/nowplaying.txt: reload=1: fontcolor=white@0.8: x=100: y=350'
videostream                | Error reinitializing filters!
videostream                | Failed to inject frame into filter network: No such file or directory
videostream                | Error while processing the decoded data for stream #0:0
videostream                | Conversion failed!
videostream exited with code 1

**Comment by ItsMitchh** [comment]
tagging myself onto this, I'll try and figure out solutions.

**Comment by bjarn** [comment]
You have to change your docker compose file, this path needs to be changed replacing azuratest_radio with your station slug:
/var/azuracast/stations/**azuratest_radio**/config/nowplaying.txt

**Comment by countrymusicfy** [comment]
@bjarn, thank you for replying, got it to work with @SC2Mitch recommendation /var/azuracast/stations/%STATION_NAME%/config/nowplaying.txt

**Comment by countrymusicfy** [comment]
also, getting youtube stream warning about increasing the bitrate, increased #VS_VBR: 1500k to 3000k but still getting warnings, will keep notching it up but overall everything seems to be working great!
