### ISSUE TITLE
Unable to stream on Youtube

### ISSUE THREAD

**Issue by idolaru** [AzuraCast/radio-video-stream#16]
Hey guys,
I am successfully running a radio stream on AzuraCast and I am trying to stream it on Youtube.

I have successfully followed the installation instructions but for some reason, the stream doesn't go live on YouTube.

I have tried restarting the stream, double checked the configuration file... everything seems fine.

Here's the configuration file sample:

`version: '2.2'

services:
  videostream:
    container_name: videostream
    build:
      context: ./videostream
    volumes:
      - station_data:/var/azuracast/stations
    restart: always
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    environment:
      # VS_VBR: 1500k
      # VS_FPS: 24
      # VS_QUALITY: superfast
      VS_RTMP_SERVER: rtmp://a.rtmp.youtube.com/live2/8w2m-d262-3c08-chs0-ahj6
      # VS_FONT_FILE: /usr/share/fonts/truetype/ubuntu/Ubuntu-B.ttf
      VS_TEXT_SOURCE: /var/azuracast/stations/azuratest_radio/config/nowplaying.txt
      # VS_TEXT_SIZE: 55
      # VS_TEXT_BOX: 1
      # VS_TEXT_BOX_COLOR: black@0.5
      # VS_TEXT_BORDER_W: 20
      # VS_TEXT_X: 100
      # VS_TEXT_Y: 350
      VS_AUDIO_SOURCE: https://electrogroove.live/radio/8000/radio.mp3
      VS_VIDEO_SOURCE: /var/azuracast/videostream/example.mp4
`

No worries about the stream-key... I'm happy to reset it.

What am I doing wrong ?

Thank you in advance for your assistance.

**Comment by idolaru** [comment]
Worth mentioning, for some reason everything works for the radio station ( except the video stream )  but I am missing the folder: /var/azuracast/stations

Not sure if this is an issue or not.

**Comment by Asthriona** [comment]
are you running the stream on the same server/instance of azura than your station?

it sounds like you are missing Azuracast.
this repo act as a plug in, you can run your instance of azura as a replay if you need or want to separate from your main station server. but you need a fully functional instance of azura in order to get this repo to work.

once the instance set up you need to replace  ```VS_TEXT_SOURCE: /var/azuracast/stations/azuratest_radio/config/nowplaying.txt```
with 
```VS_TEXT_SOURCE: /var/azuracast/stations/NAME_OF_THE_STATION/config/nowplaying.txt```
you will have the folder created once setup so you can copy past the name. 

Also please reset your tokens. it's really unsafe to post them publicly if not reset first. feel free to use dummy key instead (random letter or X instead)

**Comment by idolaru** [comment]
Thank you @Asthriona for your reply.

AzuraCast is live and running of course and the videostream is installed properly. I am using the AWS instance advertised by Azura. From server side, everything is ok.

However, I am missing  the folder /var/azuracast/stations/ 

I have seen other issues related to this where the radio is live but without the /stations/ folder.

Again, I have subscribed to the Azura software provided with AWS so I basically started the AWS instance and Azura was already installed.

No worries about the tokens... of course it has been reset :-)

**Comment by ItsMitchh** [comment]
Can you check your docker logs when you try to run the stream? It should be providing some errors for us to investigate.

**Comment by idolaru** [comment]
@SC2Mitch thank you for jumping on this. Once again, it seems something related to the missing /stations/ file but that I wouldn't know how it happened considering I purchased the an AWS Subscription provided by Azura. This shouldn't happen I suppose.

I used docker-compose logs and the latest logs look like this:

videostream                | [AVFilterGraph @ 0x558f3bc014c0] Error initializing filter 'drawtext' with args 'fontfile=/usr/share/fonts/truetype/ubuntu/Ubuntu-B.ttf: fontsize=55:      box=1: boxcolor=black@0.5: boxborderw=20:      textfile=/var/azuracast/stations/azuratest_radio/config/nowplaying.txt: reload=1: fontcolor=white@0.8: x=100: y=350'
videostream                | Error reinitializing filters!
videostream                | Failed to inject frame into filter network: No such file or directory
videostream                | Error while processing the decoded data for stream #0:0
videostream                | Conversion failed!
videostream                | ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
videostream                |   built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
videostream                |   configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
videostream                |   libavutil      55. 78.100 / 55. 78.100
videostream                |   libavcodec     57.107.100 / 57.107.100
videostream                |   libavformat    57. 83.100 / 57. 83.100
videostream                |   libavdevice    57. 10.100 / 57. 10.100
videostream                |   libavfilter     6.107.100 /  6.107.100
videostream                |   libavresample   3.  7.  0 /  3.  7.  0
videostream                |   libswscale      4.  8.100 /  4.  8.100
videostream                |   libswresample   2.  9.100 /  2.  9.100
videostream                |   libpostproc    54.  7.100 / 54.  7.100
videostream                | Input #0, lavfi, from 'movie=filename=/var/azuracast/videostream/example.mp4:loop=0, setpts=N/(FRAME_RATE*TB)':
videostream                |   Duration: N/A, start: 0.000000, bitrate: N/A
videostream                |     Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 24 fps, 24 tbr, 12288 tbn, 12288 tbc
videostream                | Input #1, mp3, from 'https://electrogroove.live/radio/8000/radio.mp3':
videostream                |   Metadata:
videostream                |     icy-br          : 128
videostream                |     icy-genre       : EDM
videostream                |     icy-name        : Electro Groove Radio
videostream                |     icy-pub         : 0
videostream                |     icy-url         : electrogroove.live
videostream                |     StreamTitle     : Eden Prince - Toxic (ft. Marco Foster)
videostream                |   Duration: N/A, start: 0.000000, bitrate: 128 kb/s
videostream                |     Stream #1:0: Audio: mp3, 44100 Hz, stereo, s16p, 128 kb/s
videostream                | Stream mapping:
videostream                |   Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
videostream                |   Stream #1:0 -> #0:1 (mp3 (native) -> mp3 (libmp3lame))
videostream                | Press [q] to stop, [?] for help
videostream                | [Parsed_drawtext_0 @ 0x558036630960] [FILE @ 0x7ffd14198cc0] Cannot read file '/var/azuracast/stations/azuratest_radio/config/nowplaying.txt': No such file or directory
videostream                | [Parsed_drawtext_0 @ 0x558036630960] The text file '/var/azuracast/stations/azuratest_radio/config/nowplaying.txt' could not be read or is empty
videostream                | [AVFilterGraph @ 0x558036634080] Error initializing filter 'drawtext' with args 'fontfile=/usr/share/fonts/truetype/ubuntu/Ubuntu-B.ttf: fontsize=55:      box=1: boxcolor=black@0.5: boxborderw=20:      textfile=/var/azuracast/stations/azuratest_radio/config/nowplaying.txt: reload=1: fontcolor=white@0.8: x=100: y=350'
videostream                | Error reinitializing filters!
videostream                | Failed to inject frame into filter network: No such file or directory
videostream                | Error while processing the decoded data for stream #0:0
videostream                | Conversion failed!
videostream                | ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
videostream                |   built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
videostream                |   configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
videostream                |   libavutil      55. 78.100 / 55. 78.100
videostream                |   libavcodec     57.107.100 / 57.107.100
videostream                |   libavformat    57. 83.100 / 57. 83.100
videostream                |   libavdevice    57. 10.100 / 57. 10.100
videostream                |   libavfilter     6.107.100 /  6.107.100
videostream                |   libavresample   3.  7.  0 /  3.  7.  0
videostream                |   libswscale      4.  8.100 /  4.  8.100
videostream                |   libswresample   2.  9.100 /  2.  9.100
videostream                |   libpostproc    54.  7.100 / 54.  7.100
videostream                | Input #0, lavfi, from 'movie=filename=/var/azuracast/videostream/example.mp4:loop=0, setpts=N/(FRAME_RATE*TB)':
videostream                |   Duration: N/A, start: 0.000000, bitrate: N/A
videostream                |     Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 24 fps, 24 tbr, 12288 tbn, 12288 tbc
videostream                | Input #1, mp3, from 'https://electrogroove.live/radio/8000/radio.mp3':
videostream                |   Metadata:
videostream                |     icy-br          : 128
videostream                |     icy-genre       : EDM
videostream                |     icy-name        : Electro Groove Radio
videostream                |     icy-pub         : 0
videostream                |     icy-url         : electrogroove.live
videostream                |     StreamTitle     : Sønlille - Light On
videostream                |   Duration: N/A, start: 0.000000, bitrate: 128 kb/s
videostream                |     Stream #1:0: Audio: mp3, 44100 Hz, stereo, s16p, 128 kb/s
videostream                | Stream mapping:
videostream                |   Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
videostream                |   Stream #1:0 -> #0:1 (mp3 (native) -> mp3 (libmp3lame))
videostream                | Press [q] to stop, [?] for help
videostream                | [Parsed_drawtext_0 @ 0x55f9ecd63960] [FILE @ 0x7ffc86508470] Cannot read file '/var/azuracast/stations/azuratest_radio/config/nowplaying.txt': No such file or directory
videostream                | [Parsed_drawtext_0 @ 0x55f9ecd63960] The text file '/var/azuracast/stations/azuratest_radio/config/nowplaying.txt' could not be read or is empty
videostream                | [AVFilterGraph @ 0x55f9ecd64b80] Error initializing filter 'drawtext' with args 'fontfile=/usr/share/fonts/truetype/ubuntu/Ubuntu-B.ttf: fontsize=55:      box=1: boxcolor=black@0.5: boxborderw=20:      textfile=/var/azuracast/stations/azuratest_radio/config/nowplaying.txt: reload=1: fontcolor=white@0.8: x=100: y=350'
videostream                | Error reinitializing filters!
videostream                | Failed to inject frame into filter network: No such file or directory
videostream                | Error while processing the decoded data for stream #0:0
videostream                | Conversion failed!
videostream                | ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
videostream                |   built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
videostream                |   configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
videostream                |   libavutil      55. 78.100 / 55. 78.100
videostream                |   libavcodec     57.107.100 / 57.107.100
videostream                |   libavformat    57. 83.100 / 57. 83.100
videostream                |   libavdevice    57. 10.100 / 57. 10.100
videostream                |   libavfilter     6.107.100 /  6.107.100
videostream                |   libavresample   3.  7.  0 /  3.  7.  0
videostream                |   libswscale      4.  8.100 /  4.  8.100
videostream                |   libswresample   2.  9.100 /  2.  9.100
videostream                |   libpostproc    54.  7.100 / 54.  7.100
videostream                | Input #0, lavfi, from 'movie=filename=/var/azuracast/videostream/example.mp4:loop=0, setpts=N/(FRAME_RATE*TB)':
videostream                |   Duration: N/A, start: 0.000000, bitrate: N/A
videostream                |     Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 24 fps, 24 tbr, 12288 tbn, 12288 tbc
videostream                | Input #1, mp3, from 'https://electrogroove.live/radio/8000/radio.mp3':
videostream                |   Metadata:
videostream                |     icy-br          : 128
videostream                |     icy-genre       : EDM
videostream                |     icy-name        : Electro Groove Radio
videostream                |     icy-pub         : 0
videostream                |     icy-url         : electrogroove.live
videostream                |     StreamTitle     : Glenn Dale - Gonna Get Your Love (Extended Edit)
videostream                |   Duration: N/A, start: 0.000000, bitrate: 128 kb/s
videostream                |     Stream #1:0: Audio: mp3, 44100 Hz, stereo, s16p, 128 kb/s
videostream                | Stream mapping:
videostream                |   Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
videostream                |   Stream #1:0 -> #0:1 (mp3 (native) -> mp3 (libmp3lame))
videostream                | Press [q] to stop, [?] for help
videostream                | [Parsed_drawtext_0 @ 0x55998b8dca80] [FILE @ 0x7fffdf81e820] Cannot read file '/var/azuracast/stations/azuratest_radio/config/nowplaying.txt': No such file or directory
videostream                | [Parsed_drawtext_0 @ 0x55998b8dca80] The text file '/var/azuracast/stations/azuratest_radio/config/nowplaying.txt' could not be read or is empty
videostream                | [AVFilterGraph @ 0x55998b8d6b80] Error initializing filter 'drawtext' with args 'fontfile=/usr/share/fonts/truetype/ubuntu/Ubuntu-B.ttf: fontsize=55:      box=1: boxcolor=black@0.5: boxborderw=20:      textfile=/var/azuracast/stations/azuratest_radio/config/nowplaying.txt: reload=1: fontcolor=white@0.8: x=100: y=350'
videostream                | Error reinitializing filters!
videostream                | Failed to inject frame into filter network: No such file or directory
videostream                | Error while processing the decoded data for stream #0:0
videostream                | Conversion failed!
videostream                | ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
videostream                |   built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
videostream                |   configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
videostream                |   libavutil      55. 78.100 / 55. 78.100
videostream                |   libavcodec     57.107.100 / 57.107.100
videostream                |   libavformat    57. 83.100 / 57. 83.100
videostream                |   libavdevice    57. 10.100 / 57. 10.100
videostream                |   libavfilter     6.107.100 /  6.107.100
videostream                |   libavresample   3.  7.  0 /  3.  7.  0
videostream                |   libswscale      4.  8.100 /  4.  8.100
videostream                |   libswresample   2.  9.100 /  2.  9.100
videostream                |   libpostproc    54.  7.100 / 54.  7.100
videostream                | Input #0, lavfi, from 'movie=filename=/var/azuracast/videostream/example.mp4:loop=0, setpts=N/(FRAME_RATE*TB)':
videostream                |   Duration: N/A, start: 0.000000, bitrate: N/A
videostream                |     Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 24 fps, 24 tbr, 12288 tbn, 12288 tbc
videostream                | Input #1, mp3, from 'https://electrogroove.live/radio/8000/radio.mp3':
videostream                |   Metadata:
videostream                |     icy-br          : 128
videostream                |     icy-genre       : EDM
videostream                |     icy-name        : Electro Groove Radio
videostream                |     icy-pub         : 0
videostream                |     icy-url         : electrogroove.live
videostream                |     StreamTitle     : Glenn Dale - Gonna Get Your Love (Extended Edit)
videostream                |   Duration: N/A, start: 0.000000, bitrate: 128 kb/s
videostream                |     Stream #1:0: Audio: mp3, 44100 Hz, stereo, s16p, 128 kb/s
videostream                | Stream mapping:
videostream                |   Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
videostream                |   Stream #1:0 -> #0:1 (mp3 (native) -> mp3 (libmp3lame))
videostream                | Press [q] to stop, [?] for help
videostream                | [Parsed_drawtext_0 @ 0x56443c38aa00] [FILE @ 0x7ffe20caa4d0] Cannot read file '/var/azuracast/stations/azuratest_radio/config/nowplaying.txt': No such file or directory
videostream                | [Parsed_drawtext_0 @ 0x56443c38aa00] The text file '/var/azuracast/stations/azuratest_radio/config/nowplaying.txt' could not be read or is empty
videostream                | [AVFilterGraph @ 0x56443c392ce0] Error initializing filter 'drawtext' with args 'fontfile=/usr/share/fonts/truetype/ubuntu/Ubuntu-B.ttf: fontsize=55:      box=1: boxcolor=black@0.5: boxborderw=20:      textfile=/var/azuracast/stations/azuratest_radio/config/nowplaying.txt: reload=1: fontcolor=white@0.8: x=100: y=350'
videostream                | Error reinitializing filters!
videostream                | Failed to inject frame into filter network: No such file or directory
videostream                | Error while processing the decoded data for stream #0:0
videostream                | Conversion failed!

**Comment by ItsMitchh** [comment]
I checked the API of your station and your using the incorrect configuration file. Try this one. 

An important note, make sure you have the video file also, it has to be the exact name, so `example.mp4`, and soforth. 

```bash
version: '2.2'

services:
  videostream:
    container_name: videostream
    build:
      context: ./videostream
    volumes:
      - station_data:/var/azuracast/stations
    restart: always
    logging:
      options: 
        max-size: "1m"
        max-file: "5"
    environment:
      # VS_VBR: 1500k
      # VS_FPS: 24
      # VS_QUALITY: superfast
      VS_RTMP_SERVER: rtmp://a.rtmp.youtube.com/live2/CHANGE-ME
      # VS_FONT_FILE: /usr/share/fonts/truetype/ubuntu/Ubuntu-B.ttf
      VS_TEXT_SOURCE: /var/azuracast/stations/electro_groove_radio/config/nowplaying.txt
      # VS_TEXT_SIZE: 55
      # VS_TEXT_BOX: 1
      # VS_TEXT_BOX_COLOR: black@0.5
      # VS_TEXT_BORDER_W: 20
      # VS_TEXT_X: 100
      # VS_TEXT_Y: 350
      VS_AUDIO_SOURCE: http://stations:8000/radio.mp3 
      VS_VIDEO_SOURCE: /var/azuracast/videostream/example.mp4
```

**Comment by Asthriona** [comment]
to be honest I'm not 100% sure this repo is still supported.

the thing that bug me is your station is live and broadcasting right?
(unable to check for myself via the link in your logs as I don't have my computer around.)
if the answer is yes, it shouldnt be possible with your missing stations/ folder. if I remember correctly that where all the data about the stations are stored. the only way that could be possible would be not running an AzuraCast/AzuraCast instance on the radio stream host.
my memory might be failing me, or can be outdated, as said in another issue my last station shutdown à while ago.
But yes this folder should definitely be present for both radio video stream and tour station to work.

**Comment by idolaru** [comment]
@SC2Mitch your solution worked. The only thing I edited was the line:

VS_TEXT_SOURCE: /var/azuracast/stations/electro_groove_radio/config/nowplaying.txt

However, I do not have the /stations/ folder which is strange.

Thank you !

**Comment by ItsMitchh** [comment]
That's intended, the `/var/azuracast/stations` is an internal container (You cant see it by default), because we use Docker, the Docker technology automatically finds that folder for you inside the Container, it's not a worry. If this issue is resolved, I can close this.

**Comment by idolaru** [comment]
> That's intended, the `/var/azuracast/stations` is an internal container (You cant see it by default), because we use Docker, the Docker technology automatically finds that folder for you inside the Container, it's not a worry. If this issue is resolved, I can close this.

Roger that! Thank you for the explanation and I hope this issue will be useful for others in the future.
