### ISSUE TITLE
Title not showing up, and some suggestion.

### ISSUE THREAD

**Issue by Siriusa77II** [AzuraCast/radio-video-stream#2]
Hey!
I played around this night with this new awesome feature!
first off all good job!
I had some issue to get it working first of all the video is a little too big and youtube dont really like 4K (and little server too) i had to re-encode it.
  
About my issue, after change the video and rebuild few times i dont know why the title on stream stop showing up. it was when the video was in 4K but not now.
now i think about it... maybe a location issue... i try to copy past the path in the file but nothing.
the nowplaying.txt have correct information. 
  

I can suggest to change it for a 1080P one (if user want to change it you can [download it here.](https://cdn.siriushd.net/example_1.mp4))
just rename it or change in your docker-compose.override.yml.  
exept this everything run smoothly on a little dedicated host! one more time good job!
![host](https://cdn.siriushd.net/putty_DUaonLfoyk.png)

ps: if you want i can create a new issue on github with suggestion. and edit this post to remove it.

**Comment by jolo22** [comment]
> Hey!
> I played around this night with this new awesome feature!
> first off all good job!
> I had some issue to get it working first of all the video is a little too big and youtube dont really like 4K (and little server too) i had to re-encode it.
> 
> About my issue, after change the video and rebuild few times i dont know why the title on stream stop showing up. it was when the video was in 4K but not now.
> now i think about it... maybe a location issue... i try to copy past the path in the file but nothing.
> the nowplaying.txt have correct information.
> 
> I can suggest to change it for a 1080P one (if user want to change it you can [download it here.](https://cdn.siriushd.net/example_1.mp4))
> just rename it or change in your docker-compose.override.yml.
> exept this everything run smoothly on a little dedicated host! one more time good job!
> ![host](https://camo.githubusercontent.com/c2434758f989e5f8633d3d88b5326b01f8751152/68747470733a2f2f63646e2e73697269757368642e6e65742f70757474795f4455616f6e4c666f796b2e706e67)
> 
> ps: if you want i can create a new issue on github with suggestion. and edit this post to remove it.

How did you manage to run it?

**Comment by Siriusa77II** [comment]
> How did you manage to run it?

I've just followed the instruction.
I'v read your youtube Live dashboard still offline righ ? please double check your stream key (aaaa-bbbb-cccc-dddd thinggy) sometime this can change for some reason.
and allow 5 minutes for the stream starting sometimes it can take time.
but let's continue this discution on your issue #1 it's not the place to discute about this :)

Btw my bad for my issue it was a location issue I set it at 0,0 it's works fine now :)
