### ISSUE TITLE
Problem during the installation 

### ISSUE THREAD

**Issue by oussamatn** [AzuraCast/radio-video-stream#4]
Hi, 

I was trying to install this script. But unfortunately it doesn't work. I can't find the folder `/var/azuracast` or the equivalent one.

Can any one help me with this?

Best,

**Comment by afonsosantos** [comment]
Hi @oussamatn 

When installing AzuraCast, you may have installed it on a different directory. `/var/azuracast` is the default and recommended for AzuraCast.
Try to find the AzuraCast installation directory by typing `sudo find / -name azuracast.env`
