### ISSUE TITLE
ffmpeg stability

### ISSUE THREAD

**Issue by starfrosch** [AzuraCast/radio-video-stream#8]
The solution is easy to install but doesn't run stable. Videostreaming quits after 6 to 48 hours of streaming. Restarting the videostream solves the problem.

Any hints on how to monitor a YouTube live broadcast to automate restarts? Maybe even better, how to stabilize streaming?

**Comment by Asthriona** [comment]
Hi, 
I'm sorry to hear that. Do you have any logs, server config, or provider by any chance? 
I remember to run it for thousands of hours with no issue. it can be anything starting by a bad configuration to an issue with your server.

**Comment by starfrosch** [comment]
I have a fresh standalone Ubuntu 20. I work around it now with my youtube live monitor.

```
!/bin/bash
#
# YouTube live broadcast monitor
#
cd /var/azuracast/videostream/
youtubeURL=https://www.youtube.com/watch?v=BiHequcIiNw
# Get YouTube Manifest 1
youtube-dl -4 -f 91 -g $youtubeURL > manifest1.txt
# Probe Manifest 1
ffprobe -v quiet -print_format json -show_streams "$(<manifest1.txt)" > json1.txt
sleep 2
youtube-dl -4 -f 91 -g $youtubeURL > manifest2.txt
ffprobe -v quiet -print_format json -show_streams "$(<manifest2.txt)" > json2.txt
# do we have a valid json
starttime=$(cat json1.txt | jq '.streams[].start_time')
if [ -z "$starttime" ]; then
  echo "$(date)" "Error: No start_time" "$starttime"
  exit 1
fi
# compare the ffprobe json, if they are the same, the live stream stopped
if cmp -s json1.txt json2.txt; then
    echo "$(date)" "Stream Down"
# restart stream
    docker-compose restart videostream
    echo "$(date)" "Stream Up"
    sleep 20
else
    echo "$(date)" "Stream Up"
fi


```

**Comment by Asthriona** [comment]
don't you prefer to fix the issue?

**Comment by starfrosch** [comment]
You can reproduce it on a Ubuntu 20 with a current Azuracast installation with CloudFlare. Then you go to Azuracast...Tools...Stream restart. This causes the videostream to die.

**Comment by starfrosch** [comment]
the -shortest option is what I added to ffmpeg streaming in broadcast.sh

Now the audio can drop and the video stream doesn't need a restart when this happens.
